### PR TITLE
Adds an action server to grab an image from a given topic before sending it on to be tweeted

### PR DESCRIPTION
**Pull request by hawesie**

### CODE REVIEW

**Comment by Jailander** [comment]
Do you want to brand the Image too? I can add a on option for branding the image

**Comment by hawesie** [comment]
If you haven’t got anything else to do, then it would be nice option to have, but it’s not a priority for me.=

**Comment by Jailander** [comment]
I might just do a copy and paste from the thing I am working on, if I have time :)

**Comment by hawesie** [comment]
Can this be merged? Any other feedback from @Jailander @cdondrup or @marc-hanheide

**Comment by cdondrup** [comment]
Looks good to me.

**Pull request merged**
