### PR TITLE
splitting datamatrix_read from qr_read_and_tweet

### PR DESCRIPTION
**Pull request by Jailander**

### CODE REVIEW

**Comment by Jailander** [comment]
see #13 more to come on that

**Comment by cdondrup** [comment]
Looks good but it has message_generation as a dependency but does not generate messages.
If you are changing that, please also remove the dependency on `opencv2`. Indigo does not support that any more. Just depend on `cv_bridge` where ever you use opencv. This will pull in the right opencv for hydro or indigo.

**Comment by Jailander** [comment]
Ok great will do

**Comment by Jailander** [comment]
this also removes qr_read_and_tweet its functionalities will remain in the devel branch of my fork until we can make it release material

**Pull request merged**
