### PR TITLE
Social card reader parameters reconfigurable.

### PR DESCRIPTION
**Pull request by gestom**

### CODE REVIEW

**Comment by marc-hanheide** [comment]
Is this used in the deployment and needed for it? Otherwise I'd leave it for after the deployment?

**Comment by gestom** [comment]
Christian mentioned that the card reader was not working well during one of the demos at AAF. This allows to increase the sensitivity of the detector in case of bad lighting conditions.

**Comment by cdondrup** [comment]
I will try this on Linda this week and merge it if it works.

**Comment by marc-hanheide** [comment]
Did you try it?

**Comment by cdondrup** [comment]
Must have forgotten, damn... But currently I don't think it's needed.

**Comment by marc-hanheide** [comment]
Still open... But as it looks sensible and passed the PR build I'll accept.

**Pull request merged**
